
import streamlit as st
import pandas as pd
import joblib
import os

st.set_page_config(
    page_title="Customer Churn Prediction",
    page_icon="📊",
    layout="centered"
)

MODEL_PATH = "customer_churn_elastic_net.joblib"

st.title("📊 Customer Churn Prediction")
st.subheader("Elastic Net Regularized Logistic Regression")
st.write("Enter the customer's details below to predict whether the customer is likely to churn.")

# Load the trained model
if not os.path.exists(MODEL_PATH):
    st.error(
        "Trained model not found. Run the final notebook cell in "
        "`Customer_Churn_Elastic_Net_Implementation.ipynb` first. "
        "It will create `customer_churn_elastic_net.joblib` in this folder."
    )
    st.stop()

model = joblib.load(MODEL_PATH)

st.markdown("### Customer Information")

col1, col2 = st.columns(2)

with col1:
    gender = st.selectbox("Gender", ["Female", "Male"])
    senior = st.selectbox("Senior Citizen", [0, 1])
    partner = st.selectbox("Partner", ["Yes", "No"])
    dependents = st.selectbox("Dependents", ["Yes", "No"])
    tenure = st.number_input("Tenure (months)", min_value=0, max_value=100, value=12)
    phone = st.selectbox("Phone Service", ["Yes", "No"])
    multiple_lines = st.selectbox("Multiple Lines", ["No", "Yes", "No phone service"])
    internet = st.selectbox(
        "Internet Service",
        ["DSL", "Fiber optic", "No"]
    )
    online_security = st.selectbox(
        "Online Security",
        ["Yes", "No", "No internet service"]
    )
    online_backup = st.selectbox(
        "Online Backup",
        ["Yes", "No", "No internet service"]
    )

with col2:
    device_protection = st.selectbox(
        "Device Protection",
        ["Yes", "No", "No internet service"]
    )
    tech_support = st.selectbox(
        "Tech Support",
        ["Yes", "No", "No internet service"]
    )
    streaming_tv = st.selectbox(
        "Streaming TV",
        ["Yes", "No", "No internet service"]
    )
    streaming_movies = st.selectbox(
        "Streaming Movies",
        ["Yes", "No", "No internet service"]
    )
    contract = st.selectbox(
        "Contract",
        ["Month-to-month", "One year", "Two year"]
    )
    paperless = st.selectbox("Paperless Billing", ["Yes", "No"])
    payment = st.selectbox(
        "Payment Method",
        [
            "Electronic check",
            "Mailed check",
            "Bank transfer (automatic)",
            "Credit card (automatic)"
        ]
    )
    monthly = st.number_input(
        "Monthly Charges",
        min_value=0.0,
        max_value=200.0,
        value=70.0,
        step=1.0
    )
    total = st.number_input(
        "Total Charges",
        min_value=0.0,
        max_value=10000.0,
        value=840.0,
        step=10.0
    )

st.divider()

if st.button("🔮 Predict Customer Churn", use_container_width=True):

    customer = pd.DataFrame([{
        "gender": gender,
        "SeniorCitizen": senior,
        "Partner": partner,
        "Dependents": dependents,
        "tenure": tenure,
        "PhoneService": phone,
        "MultipleLines": multiple_lines,
        "InternetService": internet,
        "OnlineSecurity": online_security,
        "OnlineBackup": online_backup,
        "DeviceProtection": device_protection,
        "TechSupport": tech_support,
        "StreamingTV": streaming_tv,
        "StreamingMovies": streaming_movies,
        "Contract": contract,
        "PaperlessBilling": paperless,
        "PaymentMethod": payment,
        "MonthlyCharges": monthly,
        "TotalCharges": total
    }])

    probability = model.predict_proba(customer)[0, 1]
    prediction = model.predict(customer)[0]

    st.markdown("## Prediction Result")

    st.metric(
        "Churn Probability",
        f"{probability:.2%}"
    )

    if prediction == 1:
        st.error("🔴 YES — CUSTOMER LIKELY TO CHURN")
        st.write(
            "The model identifies this customer as a potential churn customer."
        )
    else:
        st.success("🟢 NO — CUSTOMER LIKELY TO STAY")
        st.write(
            "The model does not classify this customer as likely to churn."
        )

    st.caption(
        "Prediction generated by Elastic Net Regularized Logistic Regression."
    )
